# config.yaml

constants:
  ACS_PUMS_5YEAR_LATEST: 2023
  ACS_PUMS_1YEAR_LATEST: 2023
  ACS_5YEAR_LATEST: 2023
  LODES_YEAR_LATEST: 2022
  EMPRES_LODES_WEIGHT: 0.5
  DOLLARS_2000_to_202X:
    "2021": 1.72
    "2022": 1.81
    "2023": 1.88

  years:
    - 2023
  DECENNIAL_YEAR: 2020 

geo_constants:
  BAY_AREA_COUNTY_FIPS:
    "06001": "Alameda"
    "06013": "Contra Costa"
    "06041": "Marin"
    "06055": "Napa"
    "06075": "San Francisco"
    "06081": "San Mateo"
    "06085": "Santa Clara"
    "06095": "Solano"
    "06097": "Sonoma"
  BAY_AREA_COUNTIES:
    - Alameda
    - Contra Costa
    - Marin
    - Napa
    - San Francisco
    - San Mateo
    - Santa Clara
    - Solano
    - Sonoma
  BAYCOUNTIES:
    - "001"
    - "013"
    - "041"
    - "055"
    - "075"
    - "081"
    - "085"
    - "095"
    - "097"
  STATE_CODE: "06"
  BA_COUNTY_FIPS_CODES:
    "001": "Alameda"
    "013": "Contra Costa"
    "041": "Marin"
    "055": "Napa"
    "075": "San Francisco"
    "081": "San Mateo"
    "085": "Santa Clara"
    "095": "Solano"
    "097": "Sonoma"

paths:
  tm1_root: "."
  userprofile_default: "C:/Users/YourUser"  # Replace with your actual user profile path
  box_tm_default: "C:/Box/Modeling and Surveys"
  box_tm_lzorn_drive_E: "E:/Box/Modeling and Surveys"
  pba_taz_2015: "C:/Box/Modeling and Surveys/Share Data/plan-bay-area-2050/tazdata/PBA50_FinalBlueprintLandUse_TAZdata.xlsx"
  lehd_lodes_csv: "M:/Data/Census/LEHD/Origin-Destination Employment Statistics (LODES)/LODES_Bay_Area_county_2022.csv"
  taz_sd_county_csv: "./geographies/taz-superdistrict-county.csv"
  census_api_key_file: "M:/Data/Census/API/api-key.txt"
  block2020_to_taz1454_csv: "M:/Data/GIS layers/TM1_taz_census2020/2020block_to_TAZ1454.csv"
  taz_crosswalk: "M:/Data/GIS layers/TM1_taz_census2020/TAZ1454_tract2020_crosswalk.csv"
  output_root: "./2023/outputs"
  wage_salary_csv:     "./2022/lodes_wac_employment_2022.csv"
  self_employment_csv:  "./2023/taz_self_employed_workers_2023.csv"

variables:
  ACS_BG_VARIABLES:
    tothh: B19001_001
    hhpop: B28005_001
    employed: B23025_004
    armedforces: B23025_006
    male0_4: B01001_003
    male5_9: B01001_004
    male10_14: B01001_005
    male15_17: B01001_006
    male18_19: B01001_007
    male20: B01001_008
    male21: B01001_009
    male22_24: B01001_010
    male25_29: B01001_011
    male30_34: B01001_012
    male35_39: B01001_013
    male40_44: B01001_014
    male45_49: B01001_015
    male50_54: B01001_016
    male55_59: B01001_017
    male60_61: B01001_018
    male62_64: B01001_019
    male65_66: B01001_020
    male67_69: B01001_021
    male70_74: B01001_022
    male75_79: B01001_023
    male80_84: B01001_024
    male85p: B01001_025
    female0_4: B01001_027
    female5_9: B01001_028
    female10_14: B01001_029
    female15_17: B01001_030
    female18_19: B01001_031
    female20: B01001_032
    female21: B01001_033
    female22_24: B01001_034
    female25_29: B01001_035
    female30_34: B01001_036
    female35_39: B01001_037
    female40_44: B01001_038
    female45_49: B01001_039
    female50_54: B01001_040
    female55_59: B01001_041
    female60_61: B01001_042
    female62_64: B01001_043
    female65_66: B01001_044
    female67_69: B01001_045
    female70_74: B01001_046
    female75_79: B01001_047
    female80_84: B01001_048
    female85p: B01001_049
    own1: B25009_003
    own2: B25009_004
    own3: B25009_005
    own4: B25009_006
    own5: B25009_007
    own6: B25009_008
    own7p: B25009_009
    rent1: B25009_011
    rent2: B25009_012
    rent3: B25009_013
    rent4: B25009_014
    rent5: B25009_015
    rent6: B25009_016
    rent7p: B25009_017
    white_nonh: B03002_003
    black_nonh: B03002_004
    asian_nonh: B03002_006
    total_nonh: B03002_002
    total_hisp: B03002_012
    unit1d: B25024_002
    unit1a: B25024_003
    unit2: B25024_004
    unit3_4: B25024_005
    unit5_9: B25024_006
    unit10_19: B25024_007
    unit20_49: B25024_008
    unit50p: B25024_009
    mobile: B25024_010
    boat_RV_Van: B25024_011
    employed: B23025_004
    armedforces: B23025_006
    hhinc000_010: B19001_002
    hhinc010_015: B19001_003
    hhinc015_020: B19001_004
    hhinc020_025: B19001_005
    hhinc025_030: B19001_006
    hhinc030_035: B19001_007
    hhinc035_040: B19001_008
    hhinc040_045: B19001_009
    hhinc045_050: B19001_010
    hhinc050_060: B19001_011
    hhinc060_075: B19001_012
    hhinc075_100: B19001_013
    hhinc100_125: B19001_014
    hhinc125_150: B19001_015
    hhinc150_200: B19001_016
    hhinc200p: B19001_017
    occ_m_manage:    C24010_005   # Management
    occ_m_prof_biz:  C24010_006   # Business & financial
    occ_m_prof_comp: C24010_007   # Computer, engineering & science
    occ_m_svc_comm:  C24010_012   # Community & social service
    occ_m_prof_leg:  C24010_013   # Legal
    occ_m_prof_edu:  C24010_014   # Education, training & library
    occ_m_svc_ent:   C24010_015   # Arts, design, entertainment, sports, media
    occ_m_prof_heal: C24010_016   # Healthcare practitioners & tech
    occ_m_svc_heal:  C24010_020   # Healthcare support
    occ_m_svc_fire:  C24010_022   # Fire fighting & prevention 
    occ_m_svc_law:   C24010_023   # Law enforcement
    occ_m_ret_eat:   C24010_024   # Food prep & serving
    occ_m_man_build: C24010_025   # Building & grounds cleaning
    occ_m_svc_pers:  C24010_026   # Personal care & service
    occ_m_ret_sales: C24010_028   # Sales & related
    occ_m_svc_off:   C24010_029   # Office & admin support
    occ_m_man_nat:   C24010_030   # Natural resources/construction
    occ_m_man_prod:  C24010_034   # Production & material moving
    occ_f_manage:    C24010_041   # female Management
    occ_f_prof_biz:  C24010_042   # female Business & financial
    occ_f_prof_comp: C24010_043   # female Computer, engineering & science
    occ_f_svc_comm:  C24010_048   # female Community & social service
    occ_f_prof_leg:  C24010_049   # female Legal
    occ_f_prof_edu:  C24010_050   # female Education, training & library
    occ_f_svc_ent:   C24010_051   # female Arts, entertainment, sports, media
    occ_f_prof_heal: C24010_052   # female Healthcare practitioners & tech
    occ_f_svc_heal:  C24010_056   # female Healthcare support
    occ_f_svc_fire:  C24010_058   # female Fire fighting & prevention
    occ_f_svc_law:   C24010_059   # female Law enforcement
    occ_f_ret_eat:   C24010_060   # female Food prep & serving
    occ_f_man_build: C24010_061   # female Building & grounds cleaning
    occ_f_svc_pers:  C24010_062   # female Personal care & service
    occ_f_ret_sales: C24010_064   # female Sales & related
    occ_f_svc_off:   C24010_065   # female Office & admin support
    occ_f_man_nat:   C24010_066   # female Natural resources/construction
    occ_f_man_prod:  C24010_070   # female Production & material moving
  ACS_TRACT_VARIABLES:
    hhwrks0: B08202_002
    hhwrks1: B08202_003
    hhwrks2: B08202_004
    hhwrks3p: B08202_005
    ownkidsyes: B25012_003
    rentkidsyes: B25012_011
    ownkidsno: B25012_009
    rentkidsno: B25012_017
  DHC_TRACT_VARIABLES:
    gq_inst_m_0017: PCT19_004N
    gq_noninst_m_0017_univ: PCT19_024N
    gq_noninst_m_0017_mil: PCT19_025N
    gq_noninst_m_0017_oth: PCT19_028N
    gq_inst_m_1864: PCT19_036N
    gq_noninst_m_1864_univ: PCT19_056N
    gq_noninst_m_1864_mil: PCT19_057N
    gq_noninst_m_1864_oth: PCT19_060N
    gq_inst_m_65p: PCT19_068N
    gq_noninst_m_65p_univ: PCT19_088N
    gq_noninst_m_65p_mil: PCT19_089N
    gq_noninst_m_65p_oth: PCT19_092N
    gq_inst_f_0017: PCT19_101N
    gq_noninst_f_0017_univ: PCT19_121N
    gq_noninst_f_0017_mil: PCT19_122N
    gq_noninst_f_0017_oth: PCT19_125N
    gq_inst_f_1864: PCT19_133N
    gq_noninst_f_1864_univ: PCT19_153N
    gq_noninst_f_1864_mil: PCT19_154N
    gq_noninst_f_1864_oth: PCT19_157N
    gq_inst_f_65p: PCT19_165N
    gq_noninst_f_65p_univ: PCT19_185N
    gq_noninst_f_65p_mil: PCT19_186N
    gq_noninst_f_65p_oth: PCT19_189N
  ACS_1YEAR_TARGET_VARS:
    TOTHH_target: B19001_001E   # Total households
    TOTPOP_target: B01001_001E   # Total population
    HHPOP_target: B28005_001E   # Household population
    employed: B23025_004E   # Civilian employed residents
    armedforces: B23025_006E   # Armed forces







